// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo9ln-RjqI5yzqrjDUuP32-qL7eEl6N2o',
    appId: '1:168676608976:web:761ff55dc70c276f6587d5',
    messagingSenderId: '168676608976',
    projectId: 'chat-app-abir-a4c9a',
    authDomain: 'chat-app-abir-a4c9a.firebaseapp.com',
    storageBucket: 'chat-app-abir-a4c9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-6ftI-M22RxDYNzmj5UIF7iQSB5XxEc',
    appId: '1:168676608976:android:f8b0611babf00a0b6587d5',
    messagingSenderId: '168676608976',
    projectId: 'chat-app-abir-a4c9a',
    storageBucket: 'chat-app-abir-a4c9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHVj1QwtkUx4Z3m2jR-stLcoEL5DLWExY',
    appId: '1:168676608976:ios:a7b069af2d7c148c6587d5',
    messagingSenderId: '168676608976',
    projectId: 'chat-app-abir-a4c9a',
    storageBucket: 'chat-app-abir-a4c9a.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHVj1QwtkUx4Z3m2jR-stLcoEL5DLWExY',
    appId: '1:168676608976:ios:a7b069af2d7c148c6587d5',
    messagingSenderId: '168676608976',
    projectId: 'chat-app-abir-a4c9a',
    storageBucket: 'chat-app-abir-a4c9a.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo9ln-RjqI5yzqrjDUuP32-qL7eEl6N2o',
    appId: '1:168676608976:web:5f73e3003b7d9db46587d5',
    messagingSenderId: '168676608976',
    projectId: 'chat-app-abir-a4c9a',
    authDomain: 'chat-app-abir-a4c9a.firebaseapp.com',
    storageBucket: 'chat-app-abir-a4c9a.appspot.com',
  );
}
